apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb.yml

vars:
  - name: IP_ADDRESS_POOL
    objref:
      kind: IPAddressPool
      name: my-ip-pool
      apiVersion: metallb.io/v1beta1
    fieldref:
      fieldpath: spec.addresses[0]