apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

commonLabels:
  environment: production

#resources:
#  - namespace.yaml # Define the MetalLB namespace if needed
#  - custom-config.yaml # Your custom MetalLB YAML configurations (e.g., IPAddressPool, L2Advertisement)

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    releaseName: metallb
    namespace: metallb-system
    skipHooks: false
