apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

commonLabels:
  environment: production

resources:
  - metallb_config.yml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    releaseName: metallb
    namespace: metallb-system
    skipHooks: false
